name: pd57

services:
  app:
    container_name: "pd57-app"
    build:
      context: ".docker/app"
      args:
        PHP_VERSION: "8.4"
    restart: "unless-stopped"
    volumes:
      # Internal path /var/www/glpi is a Class C framework compat path
      # (Apache DocumentRoot in base image requires it)
      - ".:/var/www/glpi:rw"
      - "custom_php_ini:/usr/local/etc/php/custom_conf.d/:rw"
    ports:
      - "8080:80"
      - "8090:8090" # E2E test server
      - "9637:9637"
    depends_on:
      - db
    environment:
      PD57_BASE_URL: http://localhost:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    container_name: "pd57-db"
    image: "mariadb:11.8"
    restart: "unless-stopped"
    volumes:
      - "db:/var/lib/mysql"
      - ".docker/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql"
    environment:
      MARIADB_ROOT_PASSWORD: "glpi"
      MARIADB_DATABASE: "pd57"
      MARIADB_USER: "glpi"
      MARIADB_PASSWORD: "glpi"
    expose:
      - "3306"

  mailpit:
    container_name: "pd57-mail"
    image: "axllent/mailpit"
    restart: "unless-stopped"
    expose:
      - "1025"
    ports:
      - "8025:8025"

  dbgate:
    container_name: "pd57-dbgate"
    image: "dbgate/dbgate:latest"
    restart: "unless-stopped"
    ports:
      - "9000:3000"
    environment:
      CONNECTIONS: "pd57"

      LABEL_pd57: "PD57 MariaDB Server"
      SERVER_pd57: "db"
      USER_pd57: "glpi"
      PASSWORD_pd57: "glpi"
      PORT_pd57: 3306
      ENGINE_pd57: "mysql@dbgate-plugin-mysql"

  # LDAP (dev/testing only)
  openldap:
    container_name: "pd57-openldap"
    image: "osixia/openldap:latest"
    restart: "unless-stopped"
    environment:
      LDAP_ORGANISATION: "Physical Desk"
      LDAP_DOMAIN: "pd57.local"
      LDAP_ADMIN_USERNAME: "admin"
      LDAP_ADMIN_PASSWORD: "admin"
    command: "--copy-service"
    volumes:
      - "./tests/LDAP/ldif/10-users.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif:rw"
      - "ldap_files:/var/lib/ldap:rw"
      - "ldap_config:/etc/ldap/slapd.d/:rw"

networks:
  default:
    name: pd57-internal

volumes:
  db:
  custom_php_ini:
  ldap_files:
  ldap_config:

